### ISSUE TITLE
[功能建议] 在关闭“自适应宽度”选项后添加“自定义宽度”的选项

### ISSUE THREAD

**Issue by PigeonP** [solstice23/lyric-bar-netease#18]
如题，在关闭“自适应宽度”选项后软件内歌词栏宽度不可自定义调整。望尽早添加此项功能。
![image](https://user-images.githubusercontent.com/108987071/236628852-06a05448-7b52-45bd-a66b-12040789b0bf.png)

**Comment by solstice23** [comment]
@PigeonP 锁定宽度吗

**Comment by PigeonP** [comment]
> @PigeonP 锁定宽度吗

是的，请问有没有能 手动调整宽度 的设置

**Comment by solstice23** [comment]
@PigeonP 把鼠标放到歌词条边缘试试

**Comment by PigeonP** [comment]
谢谢！原来一直可以调吗！我之前尝试过但似乎没看到以为没办法调整（可能是深色主题的问题我没注意到黑色的左右箭头）
![GIF 2023-5-6 22-14-10](https://user-images.githubusercontent.com/108987071/236629494-c6e78ad8-0a88-4c86-abc2-57326b6a895f.gif)
