### ISSUE TITLE
打开歌曲详情关闭后字体错位

### ISSUE THREAD

**Issue by ymy139** [solstice23/lyric-bar-netease#2]
## 描述
如题，而且如果关闭详情页后歌词未改变，显示框长度会变成最小，歌词改变后发生字体错位
## 复现操作
1. 播放一首有歌词的音乐
2. 打开歌曲详情页
3. 暂停歌曲
4. 关闭详情页
5. 显示框长度变成最小
6. 播放音乐
7. 字体错位
## 问题截图
显示框长度变成最小：
![微信图片_20230305104235](https://user-images.githubusercontent.com/117415378/222938800-4579ca27-771d-4173-bcbb-e629b9b71ec9.png)
字体错位：
![微信图片_20230305104242](https://user-images.githubusercontent.com/117415378/222938809-834b69bd-21bc-4abb-bd59-81f027b6535e.png)
## 已安装/加载插件
| RefinedNowPlaying | LyricBar | BGEnhanced | InfLink |
|  :----:  |  :----:  |  :----:  |  :----:  |
| **MoTheme** | **FiuentProgressBar** | **LibLyric** | **LibEAPIRequest** |
| **StyleSnippet** | **这首歌的封面是什么?** | **MikuPlugin** | **明/暗主题切换器** |
| **LibFrontendPlay** | **ActionEnhancement** | **SimpleAudioVisualize** | **纯净分享链接** |
| **Search on osu!** | **Customize** | **StylesheetLoader** | **LiveSongPlayer** |
***
*感觉这个问题和RefinedNowPlaying也有关，要不我去那也提一个issue?*

**Comment by solstice23** [comment]
辛苦了，还贴了一个表格
实际上修复起来就几行（
