### ISSUE TITLE
歌词错位bug

### ISSUE THREAD

**Issue by LinJie-mjyb** [solstice23/lyric-bar-netease#5]
我又来了>_<
这次是反馈bug，在进入正在播放界面前，歌词显示很正常
![image](https://user-images.githubusercontent.com/74543319/222940946-e702a5c8-8016-4881-b9d9-15367be3f0f0.png)

但是在打开“正在播放界面”后就会出现错位
![image](https://user-images.githubusercontent.com/74543319/222940964-f28123b2-239e-424f-a745-6177cac1c4b7.png)

**Comment by solstice23** [comment]
Duplicate of #2 
已修复了，等我更新
