### ISSUE TITLE
进入正在播放界面并退出后歌词栏显示不正常

### ISSUE THREAD

**Issue by ImagiToshi** [solstice23/lyric-bar-netease#6]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/79578476/222941543-5f7504c0-6a61-47c2-9695-034ab1fe090a.png">
点击底栏左侧歌曲封面再退出，主页的歌词栏会变成这种效果。稳定触发

**Comment by solstice23** [comment]
今天的第三个相同 issue，请参见上一个被关闭的 issue（
