### ISSUE TITLE
正在播放界面仍然显示歌词栏

### ISSUE THREAD

**Issue by ImagiToshi** [solstice23/lyric-bar-netease#8]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/79578476/222944064-0a7b591e-6746-425d-a41c-844b2e58f396.png">
不确定是否为bug

**Comment by solstice23** [comment]
开启了哪些选项

**Comment by ImagiToshi** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/79578476/222953168-e1507591-d2c0-4986-8fa7-f3fc3e6431bb.png">
