### ISSUE TITLE
设置界面疑似与Material You亮色主题不兼容

### ISSUE THREAD

**Issue by Yu-xiaohei** [solstice23/lyric-bar-netease#9]
> ### 刚更新到0.3.0就发现问题了😂

**同时安装Material You与本插件时，Material You选择亮色主题后本插件设置界面会出现如下图状况**
![image](https://user-images.githubusercontent.com/110207616/222945382-e289f798-7c0b-4515-98a9-2ff68bb7c439.png)
（背景为深色，文字也为黑色）

**Comment by LinJie-mjyb** [comment]
确实我刚准备反馈这个问题的
